JwtKey: 
JwtTimeoutInSeconds: 
LdapConnectionString:
OrigLdapConnectionString: 
LdapProtocolVersion:
DnsApiKey: 
DnsZones: 
VmcCspRefreshToken: 
VmcCspAuthUrl:
VmcOrg: 
VmcOrgId: 
VmcSddc:
VmcSddcId:
NsxVmxAwsApiBaseUrl:
LogFilepath:
OrigLogFilepath:
SendGridApiKey:
SendGridSenderEmail:
AWS_SES_ACCESS_KEY_ID:
AWS_SES_SECRET_ACESS_KEY:
